name: Simple Semantic Versioning
description: Automatically increments the micro portion of a semver version number in a file, on push to main. Enables manual management of minor and major portions.

branding:
  icon: git-commit
  color: orange

inputs:
  target_directory:
    description: Directory containing the version file
    required: true
  target_file:
    description: Name of the version file (must contain only a semver number, with no additional text, comments, or whitespace)
    required: true
  bump_type:
    description: Type of version bump to perform. If omitted, the micro version will be incremented.
    required: false
    options:
      - bump_minor
      - bump_major

# No outputs needed - action returns success/failure via exit code

runs:
  using: node24
  main: src/index.js
