name: Bump Minor Version
on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: true
        type: string

jobs:
  bump-minor:
    runs-on: ubuntu-latest
    env:
      TARGET_DIR: .
      TARGET_FILE: version
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            ${{ env.TARGET_DIR }}/${{ env.TARGET_FILE }}
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Bump minor version
        uses: guystrelitz/semver-bump-micro@v1.0.0
        with:
          target_directory: ${{ env.TARGET_DIR }}
          target_file: ${{ env.TARGET_FILE }}
          bump_type: bump_minor

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.TARGET_DIR }}/${{ env.TARGET_FILE }}
          git commit -m "${{ inputs.commit_message }}"
          git push

